# Generated by Django 2.1.7 on 2019-03-29 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='title',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now),
        ),
    ]
